# Generated by Django 2.1 on 2020-03-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesaje', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesaje',
            name='ticket',
        ),
        migrations.AddField(
            model_name='pesaje',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
