# Generated by Django 2.1 on 2020-03-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesaje', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesaje',
            name='fecha_salida',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pesaje',
            name='peso_neto',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='pesaje',
            name='peso_salida',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
    ]
