# Generated by Django 2.1 on 2020-03-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesaje', '0002_auto_20200331_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesajeexterno',
            name='fecha_salida',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pesajeexterno',
            name='peso_neto',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='pesajeexterno',
            name='peso_salida',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
    ]
