# Generated by Django 2.1 on 2020-03-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesaje', '0002_auto_20200321_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesaje',
            name='peso',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
