# Generated by Django 2.1 on 2020-03-31 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesaje', '0003_auto_20200331_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.CharField(default='001', max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
