# Generated by Django 2.1 on 2020-04-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesaje', '0004_producto_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesaje',
            name='fecha_ingreso',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pesaje',
            name='fecha_salida',
            field=models.DateTimeField(null=True),
        ),
    ]
