# Generated by Django 2.1 on 2020-04-02 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesaje', '0005_auto_20200401_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesaje',
            name='fecha_ingreso',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
