# Generated by Django 2.1 on 2020-04-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesaje', '0006_auto_20200401_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesaje',
            name='fecha_ingreso',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
