# Generated by Django 2.1 on 2020-04-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesaje', '0007_auto_20200401_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesajeexterno',
            name='fecha_ingreso',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pesajeexterno',
            name='fecha_salida',
            field=models.DateTimeField(null=True),
        ),
    ]
